[package]
name = "movie_cbr"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
eframe = "0.31.1"
serde ={ version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strsim = "0.11.1"
